# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables:
  build_id: $(Build.BuildId)

resources:
  pipelines:
  - pipeline: 'Deploy to Development'
    source: 'pezholio.template_test'
    trigger:
      branches:
        include:
        - "master"
        - "two-builds"

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo $(build_id)
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
